plugins {
    id "com.github.johnrengelman.shadow" version "8.1.1"
}

architectury {
    platformSetupLoomIde()
    neoForge()
}

loom {
    accessWidenerPath.set(project(":common").loom.accessWidenerPath)
}


configurations {
    common
    shadowCommon
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentNeoForge.extendsFrom common
}

dependencies {
    neoForge "net.neoforged:neoforge:${neoforge_version}"
    modApi "dev.architectury:architectury-neoforge:${architectury_version}"
    modCompileOnly "mezz.jei:jei-1.21.1-common-api:${rootProject.jei_version}"
    modCompileOnly "mezz.jei:jei-1.21.1-neoforge-api:${rootProject.jei_version}"
    modCompileOnly "me.shedaniel:RoughlyEnoughItems-api-neoforge:${rootProject.rei_version}"
    modLocalRuntime "mezz.jei:jei-1.21.1-neoforge:${rootProject.jei_version}"

    modApi("eirmax:taniwha-remaked-neoforge:${rootProject.taniwha_version}"){
        transitive = true;
        exclude group: "me.shedaniel"
        exclude group: "mezz.jei"
    }
    include("eirmax:taniwha-remaked-neoforge:${rootProject.taniwha_version}"){
        transitive = true;
        exclude group: "me.shedaniel"
        exclude group: "mezz.jei"
    }

    common(project(path: ":common", configuration: "namedElements")) { transitive false }
    shadowCommon(project(path: ":common", configuration: "transformProductionNeoForge")) { transitive = false }
}

processResources {
    inputs.property 'version', project.version

    filesMatching('META-INF/neoforge.mods.toml') {
        expand version: project.version
    }
        from(project(":common").file("src/main/resources")) {
            include "data/**"
            include "assets/**"
        }


}

shadowJar {
    exclude "fabric.mod.json"
    exclude "architectury.common.json"

    configurations = [project.configurations.shadowCommon]
    archiveClassifier = "dev-shadow"
}

remapJar {
    inputFile.set shadowJar.archiveFile
    dependsOn shadowJar
    archiveClassifier.set(null)
}

jar {
    archiveClassifier = "dev"
    archiveBaseName = "biomemakeover-neoforge"
}

sourcesJar {
    def commonSources = project(":common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}

publishing {

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
        // Add repositories to publish to here.
    }
}
